spring.application.name=NextRide_Ride

server.port=2023

spring.datasource.url=jdbc:postgresql://localhost:5432/NextRide_Ride
spring.datasource.username=postgres
spring.datasource.password=helloworld!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=helloworld!

app.jwt.secret=K9s8fJ3kL2pQx7YzWvT6bN1mR4cH8uE5dF0aSgHjKpLqZxCvBnM9tR2yUeIwOaP3
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
